# GoReleaser configuration for etu
# https://goreleaser.com

version: 2
project_name: etu
builds:
  - id: etu
    main: .
    binary: etu
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.Commit}}
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    # Format is auto-detected: tar.gz for Unix, zip for Windows
    files:
      - README.md
      - LICENSE
checksum:
  name_template: checksums.txt
snapshot:
  version_template: '{{ .Tag }}-next'
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Other Changes
      order: 999
brews:
  - name: etu
    repository:
      owner: icco
      name: homebrew-tap
    homepage: https://github.com/icco/etu
    description: A personal command line journal
    license: MIT
    test: |
      system "#{bin}/etu --version"
    install: |
      bin.install "etu"
# Release configuration
release:
  github:
    owner: icco
    name: etu
  mode: replace
  # Changelog is automatically included by GoReleaser
  header: |
    ## Changelog
  footer: |
    ---
    **Full Changelog**: https://github.com/icco/etu/compare/{{ .PreviousTag }}...{{ .Tag }}
