# GoReleaser configuration for etu
# https://goreleaser.com

version: 2
project_name: etu
builds:
  - id: etu
    main: .
    binary: etu
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.Commit}}
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    # Format is auto-detected: tar.gz for Unix, zip for Windows
    files:
      - README.md
      - LICENSE
checksum:
  name_template: checksums.txt
snapshot:
  version_template: '{{ .Tag }}-next'
changelog:
  use: git
  sort: asc
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Other Changes
      order: 999
homebrew_casks:
  - name: etu
    directory: Casks
    repository:
      owner: icco
      name: homebrew-tap
    homepage: https://github.com/icco/etu
    description: A personal command line journal
    license: MIT
    binaries:
      - etu
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/etu"]
          end
# Release configuration
release:
  github:
    owner: icco
    name: etu
  mode: replace
  footer: |
    ---
    **Full Changelog**: https://github.com/icco/etu/compare/{{ .PreviousTag }}...{{ .Tag }}
