name: Lint Checks
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  misspell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.github_token }}
          fetch-depth: 0
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          locale: US
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.github_token }}
          fetch-depth: 0
      - uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
