// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Entry struct {
	ID      string    `json:"id"`
	Created time.Time `json:"created"`
	Text    string    `json:"text"`
	User    *User     `json:"user"`
}

type NewEntry struct {
	Text    string     `json:"text"`
	Created *time.Time `json:"created"`
	UserID  string     `json:"userId"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
